a='''prabha is a good girl,
 she is learning Python!!!!'''
print(len(a))
print(a.upper())
print(a.lower())
print(a.rstrip("!"))
print(a.replace('Python','c++'))
print(a.capitalize())
print(a.count('is'))
print(a.split())
print(a.center(60))
print(a.endswith("!!!"))
print(a.find("is"))
print(a.index("is"))
print(a.isalnum())
print(a.isalpha())
print(a.islower())
b="ghjgh"
print(b.isprintable())
print(a.isspace())
print(a.istitle())
print(a.isupper())
print(a.swapcase())
print(a.title())
